var LEVEL_SCRIPT=[
  {type:'pothole',delay:2.15,first:true,w:54},
  {type:'barrier',delay:2.25},
  {type:'pothole',delay:2.05,w:72},
  {type:'truck',delay:2.45},
  {type:'pipe',delay:2.35,h:246},
  {type:'pothole',delay:2.2,w:86},
  {type:'gate',delay:2.55,gTop:150,gBottom:398},
  {type:'barrier',delay:2.1},
  {type:'truck',delay:2.35},
  {type:'pipe',delay:2.25,h:258},
  {type:'gate',delay:2.6,gTop:164,gBottom:392},
  {type:'pothole',delay:2.1,w:94},
  {type:'babushka',delay:2.25},
  {type:'gate',delay:2.55,gTop:174,gBottom:400},
  {type:'double',delay:2.8,gTop:158,gBottom:392}
];
function reset(doJump){state='play';elapsed=0;distance=0;score=0;speed=CFG.startSpeed;obstacles=[];particles=[];shake=0;flash=0;deathText='';zone=0;zoneFlash=1.7;startedHint=2.6;speechText='';speechT=0;lastSpeech=-99;roadRattleT=.6;nearMissT=0;car.y=CFG.groundY;car.vy=0;car.pitch=0;car.impact=0;car.spin=0;car.wheelRot=0;car.grounded=true;director.scriptIndex=0;director.nextSpawnT=0;director.lastType='';director.proceduralCount=0;if(audio){stepIndex=0;nextStep=audio.ac.currentTime+.05;}spawnScripted(true);if(doJump)jump(true);}
function obstacleGap(){var minGap=score<10?208:score<22?184:164,center=rand(242,340);return {top:center-minGap/2,bottom:center+minGap/2};}
function makeObstacle(type,opts){opts=opts||{};var o={type:type,x:opts.x==null?W+120:opts.x,passed:false,hit:false,first:!!opts.first};if(type==='pothole'){o.w=opts.w||88;o.y=GROUND-4;o.h=30;}if(type==='truck'){o.w=104;o.y=GROUND-86;o.h=86;}if(type==='pipe'){o.w=96;o.y=0;o.h=opts.h||258;}if(type==='gate'){var g=obstacleGap();o.w=80;o.gTop=opts.gTop==null?g.top:opts.gTop;o.gBottom=opts.gBottom==null?g.bottom:opts.gBottom;}if(type==='barrier'){o.w=58;o.y=GROUND-58;o.h=58;}if(type==='babushka'){o.w=36;o.y=GROUND-54;o.h=54;}if(type==='double'){var g2=obstacleGap();o.w=116;o.gTop=opts.gTop==null?g2.top:opts.gTop;o.gBottom=opts.gBottom==null?g2.bottom:opts.gBottom;o.offset=76;}return o;}
function spawnScripted(first){var item=LEVEL_SCRIPT[director.scriptIndex++];if(!item)return false;var o=makeObstacle(item.type,{x:first?510:W+120,first:item.first,w:item.w,h:item.h,gTop:item.gTop,gBottom:item.gBottom});obstacles.push(o);director.lastType=item.type;director.nextSpawnT=item.delay;return true;}
function chooseProcedural(){var pool=score<20?['pothole','barrier','truck','pipe','gate','babushka']:['pothole','barrier','truck','pipe','gate','babushka','double'];var type=pick(pool),tries=0;while(tries++<8&&((type==='double'&&director.lastType==='gate')||(type==='pipe'&&director.lastType==='pipe')||(type==='truck'&&director.lastType==='truck')))type=pick(pool);return type;}
function spawnProcedural(){var type=chooseProcedural(),o=makeObstacle(type,{});obstacles.push(o);director.lastType=type;director.proceduralCount++;var base=type==='double'?2.85:(type==='gate'?2.55:2.15);director.nextSpawnT=Math.max(1.65,base-score*.008)+rand(.08,.34);}
function directorUpdate(dt){director.nextSpawnT-=dt;if(director.nextSpawnT>0)return;if(director.scriptIndex<LEVEL_SCRIPT.length)spawnScripted(false);else spawnProcedural();}
function jump(isStart){car.vy=isStart?CFG.startImpulse:Math.max(car.vy+CFG.tapImpulse,CFG.maxRise);car.pitch=-.17;car.impact=.12;car.grounded=false;startedHint=0;tone(245,.028,.055,'square',audio?audio.ac.currentTime:null);haptic(7);}
function tap(){ensureAudio();if(audio&&audio.ac.state==='suspended')audio.ac.resume();if(state==='paused'){state='play';last=performance.now();return;}if(state==='title'||state==='gameover'){reset(true);return;}if(state!=='play')return;jump(false);}
function carBox(){return {x:CAR_X+CFG.carBox.x,y:car.y+CFG.carBox.y,w:CFG.carBox.w,h:CFG.carBox.h};}
function intersects(a,b){return a.x<b.x+b.w&&a.x+a.w>b.x&&a.y<b.y+b.h&&a.y+a.h>b.y;}
function collides(o){var b=carBox();if(o.type==='pothole'){var hitHalf=o.first?14:o.w*.38,left=o.x-hitHalf,right=o.x+hitHalf,low=car.y>(o.first?GROUND-43:GROUND-57),wheelX=CAR_X+46;return low&&wheelX>left&&wheelX<right;}if(o.type==='truck')return intersects(b,{x:o.x-o.w/2+5,y:o.y+2,w:o.w-10,h:o.h-2});if(o.type==='barrier')return intersects(b,{x:o.x-o.w/2+5,y:o.y,w:o.w-10,h:o.h});if(o.type==='babushka')return intersects(b,{x:o.x-o.w/2+5,y:o.y+4,w:o.w-10,h:o.h-4});if(o.type==='pipe')return intersects(b,{x:o.x-o.w/2+4,y:0,w:o.w-8,h:o.h-4});if(o.type==='gate'){var x=o.x-o.w/2+4,w=o.w-8;return intersects(b,{x:x,y:0,w:w,h:o.gTop-5})||intersects(b,{x:x,y:o.gBottom+5,w:w,h:GROUND-o.gBottom+15});}if(o.type==='double'){var x1=o.x-o.w/2,x2=x1+o.offset,a1=intersects(b,{x:x1+4,y:0,w:34,h:o.gTop-5})||intersects(b,{x:x1+4,y:o.gBottom+5,w:34,h:GROUND-o.gBottom+15}),sh=Math.sin(o.x*.01)*23,gt=clamp(o.gTop+sh,122,300),gb=clamp(o.gBottom+sh,260,400),a2=intersects(b,{x:x2+4,y:0,w:34,h:gt-5})||intersects(b,{x:x2+4,y:gb+5,w:34,h:GROUND-gb+15});return a1||a2;}return false;}
function die(o){if(state!=='play')return;state='gameover';shake=.72;flash=.16;car.spin=rand(-2.7,2.7);car.vy=-235;var ex=CAR_X+72,ey=car.y-28;burst(ex,ey,22,'#fff0ac',1.35);burst(ex,ey,22,'#ff9b35',1.2);burst(ex,ey,18,'#e8483e',1.08);burst(ex,ey,13,'#3f5165',.92);burst(CAR_X,car.y,12,'#d1d4d5',.85);metalClonk(1);suspensionCreak(.9);haptic([50,28,70]);sayGopnik('death',true);best=Math.max(best,Math.floor(distance));bestScore=Math.max(bestScore,score);store.set('nivaV4Best',best);store.set('nivaV4Score',bestScore);deathText={pothole:'POTHOLE: 1 — NIVA: 0',truck:'URAL SAYS NYET',pipe:'GOPNIK TOO TALL',gate:'CONCRETE SOCIALISM',barrier:'BARRIER SAYS BLYAT',babushka:'BABUSHKA HAS PRIORITY',double:'DOUBLE BLYAT'}[o&&o.type]||'TOO MUCH RUSSIA';}
function onPass(o){score++;tone(720,.045,.065,'square',audio?audio.ac.currentTime:null);if(score%5===0){zone=Math.min(3,zone+1);zoneFlash=1.4;sayGopnik('zone',true);}else sayGopnik('pass',false);}
function update(dt){updateParticles(dt);shake=Math.max(0,shake-dt*3);flash=Math.max(0,flash-dt);car.impact=Math.max(0,car.impact-dt);zoneFlash=Math.max(0,zoneFlash-dt);startedHint=Math.max(0,startedHint-dt);speechT=Math.max(0,speechT-dt);nearMissT=Math.max(0,nearMissT-dt);if(state==='title'||state==='paused')return;if(state==='gameover'){car.vy+=950*dt;car.y+=car.vy*dt;car.pitch+=car.spin*dt;if(car.y>CFG.groundY){car.y=CFG.groundY;car.vy*=-.15;car.spin*=.64;}return;}elapsed+=dt;distance+=speed*dt/15;speed=Math.min(CFG.maxSpeed,CFG.startSpeed+elapsed*CFG.speedRamp+score*CFG.scoreSpeed);directorUpdate(dt);car.vy+=CFG.gravity*dt;car.y+=car.vy*dt;car.wheelRot+=speed*dt*.058;car.pitch+=((clamp(car.vy/690,-.34,.43))-car.pitch)*dt*5.2;car.grounded=false;if(car.y>CFG.groundY){var landing=car.vy;car.y=CFG.groundY;car.grounded=true;if(landing>95){car.impact=.13;burst(CAR_X,GROUND-7,5,'#cfd5d8',.28);suspensionCreak(clamp((landing-80)/390,.12,.85));if(landing>280)metalClonk(.45);}car.vy=0;car.pitch*=.7;}if(car.grounded){roadRattleT-=dt;if(roadRattleT<=0){roadTick();if(Math.random()<.42)suspensionCreak(rand(.035,.085));roadRattleT=rand(.62,1.25);}}if(car.y<CFG.ceilingY){car.y=CFG.ceilingY;die({type:'pipe'});}for(var i=0;i<obstacles.length;i++){var o=obstacles[i];o.x-=speed*dt;if(!o.hit&&collides(o)){o.hit=true;die(o);break;}var passX=o.type==='double'?o.x+o.offset+26:o.x+o.w/2;if(!o.passed&&passX<CAR_X-72){o.passed=true;onPass(o);}}obstacles=obstacles.filter(function(o){return o.x>-180;});tickAudio();}
