function drawParticles(){for(var i=0;i<particles.length;i++){var p=particles[i];ctx.globalAlpha=clamp(p.life/p.max,0,1);ctx.fillStyle=p.c;ctx.fillRect(p.x-p.s/2,p.y-p.s/2,p.s,p.s);}ctx.globalAlpha=1;}
function drawSpeech(){if(speechT<=0)return;var a=clamp(speechT*2,0,1),bx=CAR_X+62,by=car.y-145;ctx.globalAlpha=a;rect(bx-8,by-8,142,38,'rgba(14,16,18,.92)');ctx.fillStyle='rgba(14,16,18,.92)';ctx.beginPath();ctx.moveTo(bx+8,by+30);ctx.lineTo(bx-3,by+49);ctx.lineTo(bx+27,by+31);ctx.fill();text(speechText,bx+63,by,17,'#fff','center');ctx.globalAlpha=1;}
function hud(){rect(18,18,250,70,'rgba(12,14,16,.82)');text(Math.floor(distance)+' m',31,27,24,'#fff');text('BEST '+best+' m',31,57,14,'#bdc6ca');text('BLYAT '+score,W/2,18,38,score?'#e8483e':'#fff','center');rect(W-82,18,64,42,'rgba(12,14,16,.82)');text(muted?'MUTE':'SOUND',W-50,29,11,muted?'#8d969a':'#efd05f','center');if(startedHint>0&&state==='play'){ctx.globalAlpha=clamp(startedHint,0,1);text('TAP POUR REMONTER — LE PREMIER TROU EST LE TUTO',W/2,104,16,'#efd05f','center');ctx.globalAlpha=1;}if(zoneFlash>0&&state==='play'){ctx.globalAlpha=clamp(zoneFlash,0,1);text(['PANELKA','TAIGA','INDUSTRIAL BLYAT','VILLAGE OF DESTINY'][zone],W-26,72,15,'#fff','right');ctx.globalAlpha=1;}}
function title(){ctx.fillStyle='rgba(0,0,0,.58)';ctx.fillRect(0,0,W,H);text('NIVA BLYAT',W/2,96,70,'#e8483e','center');text('DOOMER RUN',W/2,180,24,'#efd05f','center');text('PANELKA • GOPNIK • HARDBASS • NEIGE SALE',W/2,214,13,'#d0d7da','center');text('TAP = DÉMARRER + SAUTER',W/2,322,24,'#fff','center');text('Une Niva. Un gopnik. Une route qui te déteste.',W/2,363,15,'#d7dde0','center');}
function gameover(){ctx.fillStyle='rgba(0,0,0,.72)';ctx.fillRect(0,0,W,H);text('BLYAT.',W/2,111,70,'#e8483e','center');text(score+' PASSAGES',W/2,205,34,'#fff','center');text(deathText,W/2,268,17,'#efd05f','center');text('BEST '+bestScore,W/2,302,14,'#cbd2d5','center');text('TAP = ENCORE',W/2,374,28,'#fff','center');}
function pauseOverlay(){ctx.fillStyle='rgba(0,0,0,.7)';ctx.fillRect(0,0,W,H);text('PAUSE',W/2,205,44,'#fff','center');text('TAP POUR REPRENDRE',W/2,278,20,'#efd05f','center');}
function render(){ctx.save();if(shake>0)ctx.translate(rand(-6,6)*shake,rand(-5,5)*shake);background();for(var i=0;i<obstacles.length;i++)drawObstacle(obstacles[i]);drawParticles();drawCar();drawSpeech();hud();ctx.restore();if(flash>0){ctx.fillStyle='rgba(255,255,255,'+clamp(flash*3,0,.45)+')';ctx.fillRect(0,0,W,H);}if(state==='title')title();if(state==='gameover')gameover();if(state==='paused')pauseOverlay();}
function loop(ts){var dt=Math.min(.033,(ts-last)/1000||0);last=ts;update(dt);render();requestAnimationFrame(loop);}render();requestAnimationFrame(loop);
window.addEventListener('pointerdown',function(e){e.preventDefault();var p=canvasPoint(e);if(p.x>870&&p.y<82){ensureAudio();setMute(!muted);return;}tap();},{passive:false});
window.addEventListener('keydown',function(e){if(e.code==='Space'||e.code==='ArrowUp'){e.preventDefault();tap();}if(e.code==='KeyM'){ensureAudio();setMute(!muted);}});
document.addEventListener('visibilitychange',function(){if(document.hidden&&state==='play'){pausedByVisibility=true;state='paused';try{if(audio)audio.ac.suspend();}catch(e){}}else if(!document.hidden&&state==='paused'){pausedByVisibility=false;try{if(audio)audio.ac.resume();}catch(e){}}});
